### ISSUE TITLE
Floatline hides the last line of a multi-line printouts in Goneovim

### ISSUE THREAD

**Issue by Melkster** [windwp/floatline.nvim#10]
Usually the statusline seems to get hidden by multiline printouts, but since floatline makes the statusline persists in Goneovim, it hides the last printed line. I'm guessing that this is more a problem with how Goneovim handles floating windows, but perhaps you have an idea of what could be causing it and/or how it could be fixed.

For instance with with following command:

```vim
echo 'foo' | echo 'bar'
```

, `'bar'` gets covered by the statusline. This is however only the case in Goneovim, and not in terminal Neovim.

Here's a minimal `init.vim`:

```vim

call plug#begin('~/.config/nvim/packages/')
Plug 'windwp/floatline.nvim'
call plug#end()

lua << EOF
require('floatline').setup()
EOF
```

To test it:

```sh
goneovim -u path/to/file/above
```

**Comment by windwp** [comment]
I use https://github.com/rohit-px2/nvui/ and it working. I think goneovim make more space for cmdline.
