### ISSUE TITLE
Floatline clashes with quick-scope

### ISSUE THREAD

**Issue by Melkster** [windwp/floatline.nvim#11]
When pressing `f`/`F`/`t`/`T` with both [quick-scope](https://github.com/unblevable/quick-scope) and floatline installed, I get the following error:

```txt
Error detected while processing function quick_scope#Aim:
line   26:
Error executing vim.schedule lua callback: ...nfig/nvim/packages/floatline.nvim/lua/floatline/init.lua:140: E523: Not allowed here
```

Minimal config to reproduce:

```vim
call plug#begin('~/.config/nvim/packages/')
Plug 'windwp/floatline.nvim'
Plug 'unblevable/quick-scope'
call plug#end()

let g:qs_highlight_on_keys = ['f', 'F', 't', 'T']


lua << EOF
require('floatline').setup()
EOF
```

I have a feeling that this is an issue with floatline since I've seen similar errors with other plugins since I installed floatline.

**Comment by windwp** [comment]
i don't test but you can try disable quickscope on filetype floatline

**Comment by Melkster** [comment]
@windwp How can I do that?
