### ISSUE TITLE
Issue with indent-blankline

### ISSUE THREAD

**Issue by budswa** [windwp/floatline.nvim#3]
### Expected behavior 
It works.

### Actual behavior 
Errors out. Which results in the floatline plugin not working.
`Error detected while processing CursorMoved Autocommands for "*":
E492: Not an editor command: IndentBlanklineRefresh
packer.nvim: Error running config for lualine.nvim: .../pack/packer/start/floatline.nvim/lua/floatline/init.lua:49: Vim:E492: Not an editor command: IndentBlanklineRefresh`

Thanks

**Comment by mrjones2014** [comment]
This happened to me as well when lazy-loading the `indent-blankline` plugin.

**Comment by mrjones2014** [comment]
If you add `nofile` to the `filetype_exclude` list option and `windline` to the `buftype_exclude` option for `indent_blankline` that fixes it @budswa

**Comment by mrjones2014** [comment]
ah, never mind. still having the issue.

**Comment by windwp** [comment]
I don't have that issue maybe because i don't use packker but the solution should be disable indentline on that filetype floatline. 
I just updated it to change to floatline @mrjones2014 

I see you are using lualine. you should make an issue on lualine to implement that. it will have better performance.

**Comment by suconakh** [comment]
I managed to make floatline work with `packer`, `indent-blankline` and `feline`. I required `indent-blankline` in floatline packer specification and called indent-blankline setup function AFTER floatline
```lua
use{'windwp/floatline.nvim', requires = 'lukas-reineke/indent-blankline.nvim'}
require'floatline'.setup()
require'indent_blankline'.setup{
	char = '▏',
	buftype_exclude = {'terminal', 'nofile'},
	filetype_exclude = {'packer', 'dashboard', 'floatline'},
	show_current_context = true,
}
```
